### ISSUE TITLE
Disabled servers in config can cause json errs

### ISSUE THREAD

**Issue by jerrac** [LaneCommunityCollege/aspects_logstash_forwarder#1]
If you have something like 

``` yaml
aspects_logstash_forwarder_servers:
  prodindexer:
    use: True
    hostname: indexer1
    port: 5043
  testindexer:
    use: False
    hostname: indexer2
    port: 5043
```

The template fails to remove the ending comma as required by json.

``` json
"servers": [
                                    "indexer1:5043",
                                              ]
```
